name: Deploy Frontend to Azure Static Web Apps

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-deploy.yml"
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            return await core.getIDToken()
          result-encoding: string

      - name: Deploy Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          app_location: "./frontend"
          output_location: "./frontend"
          api_location: ""
          github_id_token: ${{ steps.idtoken.outputs.result }}
