name: Deploy Frontend to Azure Static Web Apps

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-deploy.yml"
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
	name: Build and Deploy Frontend
	permissions:
	id-token: write
	contents: read

      # 🔹 Sanity check
      - name: Debug token presence
        run: |
          if [ -z "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}" ]; then
            echo "❌ Token not found in GitHub secrets"
            exit 1
          else
            echo "✅ Token is present in GitHub secrets"
          fi

      # Deploy raw static files from /frontend (no build step)
      - name: Deploy Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          app_location: ./frontend # where index.html lives
          output_location: "./frontend" # publish directly from /frontend
          api_location: "" # backend is separate
